### ISSUE TITLE
Race condition issue with clinit

### ISSUE THREAD

**Issue by yxl** [mozilla/j2me.js#1049]
There is a race condition issue with <clinit> method if it does any asnyc operations, such as calling `Thread.sleep()`, using `synchronized` keyword.

The first time we visit a class of such async <clinit>, the VM will wait untill the async opeartions are done.
But if another thread visits the same class simultaneously, it won't wait any more.

The following is a test case to illustrate issue. 

```Java
package java.lang;

import gnu.testlet.Testlet;
import gnu.testlet.TestHarness;

class Monkey {
    public static final String name;

    static {
        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
        }
        name = "Monkey";
    }
}

public class TestStaticInitRaceCondition extends Thread implements Testlet {
    private TestHarness th;

    public void test(TestHarness th) {
        this.th = th;
        start();
        run();
    }

    public void run() {
        System.out.println(Monkey.name);
        th.check("Monkey".equals(Monkey.name));
    }
}
```
I make the &lt;clinit> of `Monkey` async by adding a `Thread.sleep()`. The main thread and a background thread acesses the static propertiy of `Monkey.name` at the same time. The main thread will waits until the &lt;clinit> finishes to get the correct monkey name, but the background thread won't wait and get a null name.

**Comment by yxl** [comment]
cc @brendandahl @mbebenita It may related to the jit compiler.

**Comment by brendandahl** [comment]
I haven't checked if it's a regression yet or if this has always been bad. With fully compiled code you'll actually end up with Monkey.name = null for the first access on both threads.

**Comment by brendandahl** [comment]
If remember correctly we decided to not handle unwinding in static initializers because it didn't happen in any real midlets. We should re enable this check https://github.com/mozilla/j2me.js/blob/master/runtime.ts#L878 though so we can see the error.

**Comment by yxl** [comment]
@brendandahl Thanks. This issue breaks a demo midlet (Cottage360) when I implement https://github.com/mozilla/j2me.js/pull/1050. That'll be good if we can fix it.
