### ISSUE TITLE
Implement streaming SHA-1 hash

### ISSUE THREAD

**Issue by EricRahm** [mozilla/j2me.js#1109]
Currently we iteratively create a copy of the buffer being hashed and then hash the entire contents at the end. This has several memory usage implications:
1. We're keeping an extra copy of the buffer around
2. We reallocate and copy the buffers on *every* iteration. This is a) slow and b) will cause heap fragmentation

**Comment by marco-c** [comment]
I have implementations of SHA-1 and MD5 in asm.js lying around, we could try using them and measuring the difference.
