### ISSUE TITLE
Investigate whether self-hosting strings improves performance on mobile

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1151]
We should investigate whether self-hosting strings (#996) had any impact on performance on mobile.

**Comment by marco-c** [comment]
@mykmelez how did your memory measurements go?

**Comment by mykmelez** [comment]
Initial measurements suggested that self-hosted strings were more expensive, but subsequent tests suggested a negligible difference. I'm wary of the measurements, which are noisy, but I suspect self-hosting strings won't make a significant difference either way, so it isn't a reason to take them (or not).
