### ISSUE TITLE
Avoid allocating memory for the bytecode of compiled methods

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1152]

**Comment by EricRahm** [comment]
If I understand correctly, this means when parsing classfiles we should not store the bytecode for methods that are already in the cache? Or do you mean something else?

**Comment by marco-c** [comment]
Yes, this is what I meant. Both methods that are in the cache and methods that are compiled ahead of time (and possibly also release memory when we're compiling a new method).

**Comment by marco-c** [comment]
With our current architecture, this would be really difficult to do.
