### ISSUE TITLE
a bunch of tests failing locally since #1172

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#1174]
#1172 passed on Travis, but tests are failing for me locally on both Mac and Linux:

> 1:1  | com.sun.cldc.i18n.TestUtfReaders-58: fail 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders-59: got (1087), expected (0) 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders-62: fail 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders-63: got (104), expected (0) 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders: 61 pass, 2 fail, 3 known fail, 0 unknown pass 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders: test expected 63 passes, got 61 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders: test expected 0 failures, got 2 
> 1:1  | com.sun.cldc.i18n.TestUtfReaders: class fail 
…
> 1:1  | com.sun.midp.io.j2me.http.TestHttpHeaders-11: fail 
> 1:1  | com.sun.midp.io.j2me.http.TestHttpHeaders: 11 pass, 1 fail, 0 known fail, 0 unknown pass 
> 1:1  | com.sun.midp.io.j2me.http.TestHttpHeaders: test expected 12 passes, got 11 
> 1:1  | com.sun.midp.io.j2me.http.TestHttpHeaders: test expected 0 failures, got 1 
> 1:1  | com.sun.midp.io.j2me.http.TestHttpHeaders: class fail 
…
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-0: fail 
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-1: got (1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-1: fail 
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-2: got (1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-2: fail 
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-3: got (1:1  | com.sun.midp.io.j2me.socket.StressTestSocket-3: fail 
>…
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket: test expected 200 passes, got 0 
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket: test expected 0 failures, got 200 
> 1:1  | com.sun.midp.io.j2me.socket.StressTestSocket: class fail 
…
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket-0: fail 
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket-1: got (1:1  | com/sun/midp/midletsuite/SuiteSettings.load.()V incomplete 
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket: 11 pass, 1 fail, 0 known fail, 0 unknown pass 
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket: test expected 12 passes, got 11 
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket: test expected 0 failures, got 1 
> 1:1  | com.sun.midp.io.j2me.socket.TestSocket: class fail 
…
> 1:1  | com.sun.midp.publickeystore.TestWebPublicKeyStore-3: fail [Unexpected exception: javax.microedition.pki.CertificateException: Certificate was issued by an unrecognized entity] 
> 1:1  | javax.microedition.pki.CertificateException: Certificate was issued by an unrecognized entity 
> 1:1  |  - javax/microedition/pki/CertificateException.<init>(), bci=0 
> 1:1  |  - com/sun/midp/pki/X509Certificate.verifyChain(), bci=0 
> 1:1  |  - com/sun/midp/pki/X509Certificate.verifyChain(), bci=0 
> 1:1  |  - com/sun/midp/publickeystore/TestWebPublicKeyStore.test(), bci=0 
> 1:1  |  - RunTests.runTest(), bci=0 
> 1:1  |  - RunTests.startApp(), bci=0 
> 1:1  |  - javax/microedition/midlet/MIDletTunnelImpl.callStartApp(), bci=0 
> 1:1  |  - com/sun/midp/midlet/MIDletPeer.startApp(), bci=0 
> 1:1  |  - com/sun/midp/midlet/MIDletStateHandler.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/AbstractMIDletSuiteLoader.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/CldcMIDletSuiteLoader.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/AbstractMIDletSuiteLoader.runMIDletSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/MIDletSuiteLoader.main(), bci=0 
> 1:1  |  - com/sun/midp/pki/X509Certificate.verifyChain(), bci=170 
> 1:1  |  - com/sun/midp/pki/X509Certificate.verifyChain(), bci=8 
> 1:1  |  - com/sun/midp/publickeystore/TestWebPublicKeyStore.test(), bci=309 
> 1:1  | com.sun.midp.publickeystore.TestWebPublicKeyStore: 3 pass, 1 fail, 0 known fail, 0 unknown pass 
> 1:1  | com.sun.midp.publickeystore.TestWebPublicKeyStore: test expected 0 failures, got 1 
> 1:1  | com.sun.midp.publickeystore.TestWebPublicKeyStore: class fail 
…
> 1:1  | gnu.testlet.java.io.PrintStreamTest-1: fail 
> 1:1  | gnu.testlet.java.io.PrintStreamTest-2: got (truefalseￅﾛￄﾇx￥ﾆﾷ-3.78-8430948308430948307ￅﾛciￃﾳￅﾂka 
> 1:1  | true 
> 1:1  | y 
> 1:1  | ￄﾇx￥ﾆﾷ 
> 1:1  | 7.5 
> 1:1  | -999 
> 1:1  | -894384038080312 
> 1:1  | 7 
> 1:1  | test 
> 1:1  | xA0Ac), expected (1:1  | gnu.testlet.java.io.PrintStreamTest: 1 pass, 1 fail, 0 known fail, 0 unknown pass 
> 1:1  | gnu.testlet.java.io.PrintStreamTest: test expected 2 passes, got 1 
> 1:1  | gnu.testlet.java.io.PrintStreamTest: test expected 0 failures, got 1 
> 1:1  | gnu.testlet.java.io.PrintStreamTest: class fail 
…
> 1:1  | javax.microedition.io.file.TestFileConnection-141: fail [Unexpected exception: java.lang.IllegalArgumentException: Root is not specified] 
> 1:1  | java.lang.IllegalArgumentException: Root is not specified 
> 1:1  |  - javax/microedition/io/file/TestFileConnection.test(), bci=0 
> 1:1  |  - RunTests.runTest(), bci=0 
> 1:1  |  - RunTests.startApp(), bci=0 
> 1:1  |  - javax/microedition/midlet/MIDletTunnelImpl.callStartApp(), bci=0 
> 1:1  |  - com/sun/midp/midlet/MIDletPeer.startApp(), bci=0 
> 1:1  |  - com/sun/midp/midlet/MIDletStateHandler.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/AbstractMIDletSuiteLoader.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/CldcMIDletSuiteLoader.startSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/AbstractMIDletSuiteLoader.runMIDletSuite(), bci=0 
> 1:1  |  - com/sun/midp/main/MIDletSuiteLoader.main(), bci=0 
> 1:1  |  - javax/microedition/io/file/TestFileConnection.test(), bci=1319 
> 1:1  | javax.microedition.io.file.TestFileConnection: 141 pass, 1 fail, 0 known fail, 0 unknown pass 
> 1:1  | javax.microedition.io.file.TestFileConnection: test expected 167 passes, got 141 
> 1:1  | javax.microedition.io.file.TestFileConnection: test expected 0 failures, got 1 
> 1:1  | javax.microedition.io.file.TestFileConnection: class fail 

A bunch of IBM TCK tests also fail:

> :1  | 357 tests, 235 passed, 39 excluded, 83 failed

**Comment by mykmelez** [comment]
Hmm, the Travis run didn't actually succeed, Travis just reported incorrectly:

https://travis-ci.org/mozilla/j2me.js/builds/52324744

I'll revert the merge.

**Comment by marco-c** [comment]
I wonder why Travis is reporting a success :/
