### ISSUE TITLE
Investigate storing a parsed structure instead of the raw data for classes in JARStore

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1186]
Right now, we're storing raw class data in JARStore. We could instead store already parsed ClassInfo objects.

**Comment by mbebenita** [comment]
We should not "parse" class files into JS data structures in the first place. We should just interpret the class file data structure as is. I'm actively working on a PR to do this, and I can use some help. I think time would be better spent on that instead of this bug.

**Comment by marco-c** [comment]
Yeah, whether we do this or not (and how) definitely depends on the results of #1063.

**Comment by mbebenita** [comment]
I put up a WIP PR #1188 that tries to do this.

**Comment by mykmelez** [comment]
> We should not "parse" class files into JS data structures in the first place. We should just interpret the class file data structure as is. I'm actively working on a PR to do this, and I can use some help.

#1063 is important; how can we help?

**Comment by marco-c** [comment]
We're directly using the class file format now.
