### ISSUE TITLE
Some optimizations applied by the baseline JIT aren't compatible with caching

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1321]
In the baseline JIT, emitClassInitializationCheck is not emitting the initialization check if a class is already initialized.
When loaded from the cache, the method could fail if the class doesn't get initialized before the method runs.

**Comment by marco-c** [comment]
@mbebenita suggested we should store assumptions as well in the cache and checking them when loading a method.

**Comment by brendandahl** [comment]
I assume you're talking about the code at https://github.com/mozilla/j2me.js/blob/3dc70eb04f78f91b06d39aa7e200a4e762b28210/jit/baseline.ts#L860

When the cache is enabled the target is set to STATIC so the code should be fine. https://github.com/mozilla/j2me.js/blob/3dc70eb04f78f91b06d39aa7e200a4e762b28210/vm/runtime.ts#L1726

**Comment by brendandahl** [comment]
I should note that we should remove optimization if we ever do use Runtime, because a class may be initialized in one runtime but not the other.

**Comment by marco-c** [comment]
Right, I didn't notice we aren't optimizing the class initialization check away when the cache is enabled.
