### ISSUE TITLE
optimize DirectUtils::createImage

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#1349]
The [custom implementation of DirectUtils::createImage](https://github.com/mozilla/j2me.js/blob/b831401e0eaeef3e114d325334d4c7a749f8d5bb/java/custom/com/nokia/mid/ui/DirectUtils.java#L13-L23) says:

> There's room for optimization here, we're creating an image
> filling it with a blank rect (because Image::createImage(int width, int height)
> calls ImageDataFactory::createOffScreenImageData(int width, int height), that
> in turn calls ImageDataFactory::createMutableImageData(ImageData data, int width, int height)).
> In the setPixels native we're ditching the canvas created in createMutableImageData and
> we're creating a new canvas.

So let's optimize it!

**Comment by marco-c** [comment]
I think @TimAbraldes was doing this in https://github.com/mozilla/j2me.js/pull/1277 (that he's now splitting in several PRs)

**Comment by TimAbraldes** [comment]
Yup! This is one of the things that that PR accomplished. It will be included in one of the smaller PRs that comes out of that work

**Comment by TimAbraldes** [comment]
This is included in #1395
