### ISSUE TITLE
j2me.js doesn't start after deleting database

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1362]
I think this is a regression in Firefox 40.
After hitting "Delete Database" and reloading the page, j2me.js doesn't start. There's no error in the console.
The only way to make it work again is by removing the storage files from the Firefox profile.

This isn't reproducible on file:// pages.

**Comment by marco-c** [comment]
This might have something to do with the recent IndexedDB changes in Firefox: https://groups.google.com/forum/#!topic/mozilla.dev.platform/3IqDew1O-Vk

**Comment by mykmelez** [comment]
FWIW, I'm not seeing this on my Mac. I can run a midlet, press Delete Database, and then reload the page to re-run the midlet without any problem.

**Comment by marco-c** [comment]
It's working now, probably a regression that has been fixed.
