### ISSUE TITLE
`Graphics` objects returned from distinct calls to `Image.getGraphics` should not interfere with each other

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/j2me.js#1383]
https://docs.oracle.com/javame/config/cldc/ref-impl/midp2.0/jsr118/javax/microedition/lcdui/Image.html#getGraphics%28%29

If I'm reading that doc correctly, every call to `Image.getGraphics` must return a newly-created `Graphics` object that is in the default state for new `Graphics` objects. Changing (e.g.) the clipping rectangle of one returned `Graphics` object should not affect the clipping rectangle of the other `Graphics` object.

In our current implementation, the `Graphics` objects returned from a single `Image`'s `getGraphics` method share an HTML Canvas 2D Context, which means that the properties of `Graphics` objects obtained from `Image.getGraphics` might be out of sync with the underlying canvas context, and that changing the properties of one `Graphics` object might affect other `Graphics` objects. For example:

    Image img;
    Graphics g1 = img.getGraphics();
    g1.setColor(255, 0, 0);
    Graphics g2 = img.getGraphics();
    // This will return 0 since this `Graphics` object is in the
    // default state (where the color is black)
    g2.getRedComponent();
    // However, this will paint a red rect
    g2.fillRect(0, 0, 25, 25);

    g2.clipRect(25, 25, 25, 25);
    // This will be clipped but it should not be
    g1.fillRect(0, 0, 100, 100);

**Comment by marco-c** [comment]
You could verify your findings by writing a simple MIDlet and testing it in the Nokia simulator and comparing the results with j2me.js.
I have already installed it, so if you write the MIDlet I can test it for you (both on the Nokia simulator and on a real device, if I manage to install MIDlets on my real device again)

**Comment by TimAbraldes** [comment]
> You could verify your findings by writing a simple MIDlet and testing it in the Nokia simulator and comparing the results with j2me.js.
> I have already installed it, so if you write the MIDlet I can test it for you (both on the Nokia simulator and on a real device, if I manage to install MIDlets on my real device again)

I've added a `TestImageGraphics` MIDlet in the "testlets" directory in https://github.com/TimAbraldes/j2me.js/tree/testImageGraphics

I'm not sure how to build it yet but it should basically test what we want to test

**Comment by TimAbraldes** [comment]
Figured out that it builds whenever I `make`. Rebase and updated; I expect that with the simulator you'll see two red squares in an otherwise green canvas. On j2me.js I see just one red square (though that's better than I thought we'd do; I didn't expect to see any red squares).

**Comment by marco-c** [comment]
![result](https://cloud.githubusercontent.com/assets/1616846/7032215/8c65cacc-dd71-11e4-855e-c0e31c68d7f6.png)

**Comment by TimAbraldes** [comment]
So that confirms that our `Graphics` objects should not be interfering with each other. Created #1395 which fixes this issue. I've moved the test that was originally in my TestImageGraphics branch into a gfx test in the PR
