### ISSUE TITLE
enable socket tests

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#141]
We landed support for sockets with tests that are marked as *todo* because the test page needs tcp-socket permission to access mozTCPSocket, and we can't yet set that permission for the page in SlimerJS. See [this conversation about fixes for the problem](https://groups.google.com/forum/?pli=1#!topic/slimerjs/xGmEyvUIf90). Once SlimerJS supports granting tcp-socket to the page, we should enable the tests.

**Comment by marco-c** [comment]
While I was doing #1131, I've done this as well (in #1132).
