### ISSUE TITLE
BubbleSort benchmark is 2.5X faster in debug mode than in release mode, in the jsshell.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#1479]
Something is fishy here.

**Comment by mbebenita** [comment]
Bisected this down to an optimization in closure `coalesceVariableNames`.

**Comment by mbebenita** [comment]
@mykmelez the closure compiler should be updated to this commit: https://github.com/mbebenita/closure-compiler/commit/2b3ea8b8ea0aea2cb83a35519470712e21b654c0

**Comment by mykmelez** [comment]
Note that this is jsshell-specific. It doesn't show up in the browser. Nevertheless, #1480 will fix it.
