### ISSUE TITLE
Try starting the FG MIDlet before the BG MIDlet

### ISSUE THREAD

**Issue by marco-c** [mozilla/j2me.js#1510]

**Comment by TimAbraldes** [comment]
Launching the FG MIDlet before the BG MIDlet didn't work out in my testing; it causes the FG MIDlet to run in the AMS isolate so when the FG MIDlet tries to shut down (taking the AMS isolate with it), we're no longer able to send messages to the AMS isolate that would re-launch the FG MIDlet.
