### ISSUE TITLE
modify startup benchmark to measure warm startup time

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#1521]
We should modify the startup benchmark to measure warm startup time.

It already differentiates between the VM, BG midlet, and FG midlet startup times, and perhaps the FG number is a rough equivalent. But I want to make sure we have an accurate measure of the warm startup time--and label it as such--so we can track its change and measure our progress reducing it.

**Comment by mykmelez** [comment]
(Even if the FG midlet startup time measurement is reasonable accurate now, it won't be after #1512.)

**Comment by marco-c** [comment]
It isn't too accurate as it is, because it includes time spent in the BG MIDlet (because the BG MIDlet is still being initialized when it starts the FG MIDlet).

**Comment by marco-c** [comment]
Fixed by https://github.com/mozilla/j2me.js/pull/1523.
