### ISSUE TITLE
add diagram to readme and wiki

### ISSUE THREAD

**Issue by wfwalker** [mozilla/j2me.js#1530]
add this diagram to readme and wiki

![j2me-timelines-2](https://cloud.githubusercontent.com/assets/812428/7572315/0a3a174e-f7d2-11e4-811d-5e1a38caa439.png)

**Comment by wfwalker** [comment]
see https://github.com/mozilla/j2me.js/wiki/Install,-Cold,-and-Warm-runs

**Comment by marco-c** [comment]
Fixed by https://github.com/mozilla/j2me.js/pull/1531.
