### ISSUE TITLE
Ensure that all natives use the proper calling convention.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#1580]
The new design changes the calling convention for longs. Longs are now passed as two arguments, a low and high value. The proper way to implement a native with the signature "identity.(J)J" is:
```typescript
function identity(yL: number, yH: number) {
  return returnLong(yL, yH);
}
```
`returnLong` is defined as:
```typescript
export function returnLong(l: number, h: number) {
  tempReturn0 = h;
  return l;
}
```

Any function that calls a native that returns a long must read the high part of the long from the global `tempReturn0` variable.

**Comment by mykmelez** [comment]
Fixed by https://github.com/mozilla/j2me.js/commit/f5cb9f6a39f403a1795238643eb055afabca5a6b.
