### ISSUE TITLE
"TypeError: navigator.mozSetMessageHandler is not a function" on desktop

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#1617]
Loading j2me.js on desktop throws "TypeError: navigator.mozSetMessageHandler is not a function" now that Content opens *mozActivityHandler*, which calls *navigator.mozSetMessageHandler*. The code should check if it's available before calling it. Or we should mock it on desktop.

(There's also a call to *navigator.mozSetMessageHandler* in the *backgroundCheck* opener, but it depends on *navigator.mozAlarms* which isn't present on desktop, so it never gets called there.)

**Comment by marco-c** [comment]
Fixed by https://github.com/mozilla/j2me.js/pull/1618.
