### ISSUE TITLE
bld/j2me-jsc.js:556: ReferenceError: printErr is not defined

### ISSUE THREAD

**Issue by bgirard** [mozilla/j2me.js#1623]
I get the following when building on OSX using the instructions in the README.

**Comment by marco-c** [comment]
You probably have an old version of SpiderMonkey installed. I'm currently using JavaScript-C37.0a1.

(It's not specified in the README, but you also need SpiderMonkey)

**Comment by marco-c** [comment]
https://github.com/mozilla/j2me.js/issues/1624 will automatically download an updated version of SpiderMonkey when you run *make*.

**Comment by mykmelez** [comment]
@bgirard I just merged #1624, so if you pull from upstream, then you shouldn't see this problem anymore. Please reopen if you still do!

**Comment by bgirard** [comment]
Works great!

FWIW I tried to update js, which I noticed was installed via brew but I was using the latest brew version.

**Comment by mykmelez** [comment]
Yes, the [current brew](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/spidermonkey.rb) is 1.8.5:

> 06-05 09:34 > brew info spidermonkey
> spidermonkey: stable 1.8.5 (bottled), HEAD
> JavaScript-C Engine
> https://developer.mozilla.org/en/SpiderMonkey
> Conflicts with: narwhal
> Not installed
> From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/spidermonkey.rb
> ==> Dependencies
> Required: readline ✔, nspr ✔

Which is a perfectly reasonable version to use. We should figure out why it busts builds. So I'm going to reopen this issue to track that work!

**Comment by marco-c** [comment]
Well, SpiderMonkey 1.8.5 shipped with Firefox 4.0 (according to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases/1.8.5), I guess we don't need to support it.

**Comment by mykmelez** [comment]
> Well, SpiderMonkey 1.8.5 shipped with Firefox 4.0 (according to https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/Releases/1.8.5), I guess we don't need to support it.

Hmm, indeed, that was forever ago. I wonder why Homebrew hasn't been updated. In any case, let's not worry about this then.
