### ISSUE TITLE
switch to Forge's SHA-1 implementation

### ISSUE THREAD

**Issue by mykmelez** [mozilla/j2me.js#173]
We currently use Rusha to generate SHA-1 message digests, but we're switching from CryptoJS to Forge for MD5 over in #170, and Forge code appears to be more mature than Rusha (in particular, it contains many more comments), while the project seems more active.

Provided the MD5 switch goes well, we should switch our SHA-1 implementation to Forge too.

Note this [performance comparison paper](http://dominictarr.github.io/crypto-bench/) comparing the two libaries (and others).

**Comment by marco-c** [comment]
We now have an implementation written in Java (#1117).
