### ISSUE TITLE
Attempt to align TypedArray usage

### ISSUE THREAD

**Issue by EricRahm** [mozilla/j2me.js#565]
For Java we need to represent byte arrays as signed chars according to the [spec](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html), so we use an Int8Array. 

In ```fs.FileBuffer``` [we use a UInt8Array](https://github.com/andreasgal/j2me.js/blob/master/libs/fs.js#L30) for holding file data (I don't think there's a background reason for this other than that's a pretty common interpretation of what a byte array should be). 

This leads to unnecessary conversion in the underlying TypedArray copying code. We should look into switching ```fs.FileBuffer``` to Int8Array (or maybe just an ArrayBuffer) to avoid the unnecessary conversion. There are probably other areas that could benefit from this, we should audit the usage of TypedArrays throughout the codebase and file followups as necessary.

**Comment by marco-c** [comment]
Done with https://github.com/mozilla/j2me.js/pull/1024 and https://github.com/mozilla/j2me.js/pull/1034.
