### ISSUE TITLE
Correctly handle foreground/background events for multiple MIDlets within a JAR

### ISSUE THREAD

**Issue by TimAbraldes** [mozilla/j2me.js#823]
A JAR can contain multiple MIDlets that will run simultaneously. Each one has a `Display` object and an associated current `Displayable`. Only the foreground MIDlet's current `Displayable` should be visible at any given time.

In our implementation, all running MIDlets draw to the "display" simultaneously, regardless of whether they are in the foreground or background. This causes problems if, for example, the background MIDlet sets its current Displayable (it will draw over the foreground MIDlet).

Our implementation should work correctly with multiple MIDlets in a JAR - drawing only the foreground MIDlet's current Displayable but still keeping track of all required state for each MIDlet (even the background ones).

**Comment by marco-c** [comment]
I'd guess background MIDlets aren't going to use the display, but we should keep this issue in mind in case some MIDlet will decide to do it.

**Comment by TimAbraldes** [comment]
This is the same as #1384. Closing this bug in favor of that one since that has a more accurate description
