### ISSUE TITLE
Remove util.js Creation Methods

### ISSUE THREAD

**Issue by brendandahl** [mozilla/j2me.js#863]
1) Refactor calls to newPrimitiveArray to use J2ME.newArray
2) Remove newArray and refactor/replace calls with J2ME.newArray
3) Remove newObject and refactor/replace calls with J2ME.newObject
4) Remove newString and replace calls with J2ME.newString
5) Remove fromJavaString and replace calls with J2ME.fromJavaString

**Comment by marco-c** [comment]
Only fromJavaString and fromJavaChars are remaining now.
