### ISSUE TITLE
Replace old field access pattern with the new bindings mechanism. 

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#922]
The way we currently access fields from native code is incredibly inefficient, for instance, in `gfx::withClip` we use:

```
g.klass.classInfo.getField("I.clipX1.S").get(g)
```

This should be rewritten as:

```
g.clipX1
```
See #853 for details on how to do this.

To see which call sites are most frequent, modify `getField` in actors.ts to keep a count of them:

```
getField(fieldKey: string) : FieldInfo {
  runtimeCounter.count("getField " + Debug.backtrace().split("\n")[1]);
  return CLASSES.getField(this, fieldKey);
}
```
Click the `Dump Counters` button to view the counters.

**Comment by marco-c** [comment]
Fixed by #1283.
