### ISSUE TITLE
Overriding Java methods in JS can be significantly slower. 

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#967]
This micro benchmark:
```
int size = 1024 * 256;
ByteArrayOutputStream stream = new ByteArrayOutputStream();
for (int i = 0; i < size * 32; i++) {
  stream.write(i);
  stream.write(i);
  stream.write(i);
  stream.write(i);
}
```
is nearly 50x slower if we override the `ByteArrayOutputStream.write` method in JS. The JIT can do a slightly better job here because it doesn't need getters and setters to access Java fields. This alone doesn't explain the huge perf difference, and it's most likely some weird inlining behavior. We should not override Java methods in JS unless we really have to, it's both error prone and not necessarily faster. I'd even go as far as to say that we should move more code to Java than the other way around, where it makes sense.

I should add that I'm comparing against the relooper JIT.

JS Version:
```
Override["java/io/ByteArrayOutputStream.write.(I)V"] = function(value) {
  var count = this.count;
  var buf = this.buf;

  var newcount = count + 1;
  if (newcount > buf.length) {
    var newbuf = J2ME.newByteArray(Math.max(buf.length << 1, newcount));
    newbuf.set(buf);
    buf = newbuf;
    this.buf = buf;
  }

  buf[count] = value;
  this.count = newcount;
};
```

JIT Version:
```
function java_io_ByteArrayOutputStream_write_GBkt13jE(b) {
var re;
var a, b, c, d;
a = this;
var A, B, C, D, E;
var pc = 0;
var label = 0;
 A = a;
 A = A.$count;
 B = 1;
 A = A + B | 0;
 c = A;
 A = c;
 B = a;
 B = B.$buf;
 B = B.length;
 if (!(A <= B)) {
  A = a;
  A = A.$buf;
  A = A.length;
  B = 1;
  A = A << B;
  B = c;
  re = java_lang_Math_max_G_$iBibF(A, B);
  A = re;
  A = new Int8Array(A);
  d = A;
  A = a;
  A = A.$buf;
  B = 0;
  C = d;
  D = 0;
  E = a;
  E = E.$count;
  re = java_lang_System_arraycopy_G_4mLmaq(A, B, C, D, E);
  A = a;
  B = d;
  A.$buf = B;
 }
 A = a;
 A = A.$buf;
 B = a;
 B = B.$count;
 C = b;
 C = (C << 24) >> 24;
 CAB(A, B);
 A[B] = C;
 A = a;
 B = c;
 A.$count = B;
 return;
}

```

**Comment by marco-c** [comment]
I think this isn't always true, so we should analyze on a case-by-case basis.
For example the gesture classes are faster in JS than in Java (the JIT wasn't generating such a good code).
Other cases where this isn't true is when we change the behavior of the class to make it faster (for example, com/sun/midp/security/Permissions) or when we don't access Java properties (for example, the Graphics class)

**Comment by marco-c** [comment]
We've self-hosted a few classes (and we're about to self-host strings). I've removed almost all overrides and will soon remove support for overriding without natives.
