### ISSUE TITLE
Monitor Exit / Enter are slow.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/j2me.js#994]
Our current implementation is pretty slow and allocates lots of memory. This should be changed to be very fast for the common case:

monitorEnter: there is no lock 
monitorExit: there is a lock at level 1 and nobody is blocked on us.

The lock should be cached on the object and not reallocated over and over again as is the case now. Additionally, the new implementation should make it easy for the JIT to inline the common path.

This is pretty important, since some midlets, we can easily perform 30K+ monitor enters when scrolling lists.

**Comment by mbebenita** [comment]
We only attach a `_lock` property on objects that we've locked on. This is bad because it can mess up the shape cache for these objects. We should add the `_lock` property on all objects in the VM, (the same way `_hashCode` is done). The same is true for the `waiting` and `ready` queues. We should move these properties to the object lock.

**Comment by marco-c** [comment]
Fixed by https://github.com/mozilla/j2me.js/pull/1028.
